[AVATARS]
user = "https://libapps.sjsu.edu/kingbot/app/static/user_icon.png"
assistant = "https://libapps.sjsu.edu/kingbot/app/static/kingbot_icon.png"

[ROLES]
user = "user"
assistant = "assistant"

[main]
title = "SunDevil Library Chat ðŸ”±"
logo = "![Kingbot](./app/static/sundevil.png)"

[side]
title = "[![ASU Library](./app/static/asu_library_logo.png)](https://lib.asu.edu/)"
intro = "SunDevil Library Chat is a workshop demonstration of an AI-powered assistant designed to help users with general questions about Arizona State University (ASU) Library services. This tool is not an official ASU Library service and does not replace librarians or library staff."
policylink = "https://lib.asu.edu/"
policylabel = "See SunDevil Library Chat Policy"

[button1]
label = "ASU Library Hours"
content = "How can I find ASU Library hours?"
chip = "SC: Hours"

[button2]
label = "Start Your Research"
content = "How do I start my research using ASU Library resources?"
chip = "SC: ResearchStart"

[button3]
label = "Borrow A Laptop"
content = "How do I borrow a laptop from ASU Library"
chip = "SC: BorrowLaptop"