[client]
showErrorDetails = false

[global]
showWarningOnDirectExecution = false

[browser]
serverAddress = "localhost"
gatherUsageStats = false

[server]
enableCORS = false
enableXsrfProtection = false
fileWatcherType = "none"
enableStaticServing = true

[theme]
primaryColor = "#8C1D40"          
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F7F7F7"
textColor = "#1E1E1E"
font = "sans serif"

